#!/bin/bash
# channel.sh
# Sets up the channel and joins peers

# Import shared variables
source ./env.sh

print_step "Step 1: Creating Channel Block..."
# Note: We use the .tx file generated by network.sh
peer channel create -o $ORDERER_ADDRESS -c $CHANNEL_NAME -f ./channel-artifacts/${CHANNEL_NAME}.tx --outputBlock ./channel-artifacts/${CHANNEL_NAME}.block --tls --cafile $ORDERER_CA
sleep 2

print_step "Step 2: Joining Peer0 to Channel..."
peer channel join -b ./channel-artifacts/${CHANNEL_NAME}.block
sleep 2

print_step "Step 3: Updating Anchor Peers..."
peer channel update -o $ORDERER_ADDRESS -c $CHANNEL_NAME -f ./channel-artifacts/Org1MSPanchors.tx --tls --cafile $ORDERER_CA
sleep 2

echo -e "${GREEN}Channel Setup Complete!${NC}"